name: PR standards

on:
  pull_request:
    branches: [ main ]

jobs:
  pr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Check version has changed
      run: .github/scripts/check-version-change.sh
