name: Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: [1.1.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry ${{ matrix.poetry-version }}
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest .

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Set up Poetry 1.1.12
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.12"
    - name: Install dependencies
      run: |
        poetry install
    - name: Check typing with mypy
      run: |
        poetry run mypy .
    - name: Check style with flake8
      run: |
        poetry run flake8
    - name: Check formatting with black
      run: |
        poetry run black --check .
    - name: Check import ordering with isort
      run: |
        poetry run isort --check .
